-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 12:01:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema NSTP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `NSTP` ;

-- -----------------------------------------------------
-- Schema NSTP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NSTP` ;
-- -----------------------------------------------------
-- Schema class_staff
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `class_staff` ;

-- -----------------------------------------------------
-- Schema class_staff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `class_staff` DEFAULT CHARACTER SET latin1 ;
USE `NSTP` ;

-- -----------------------------------------------------
-- Table `NSTP`.`Class_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NSTP`.`Class_staff` ;

CREATE TABLE IF NOT EXISTS `NSTP`.`Class_staff` (
  `ClassCode` INT NOT NULL AUTO_INCREMENT,
  `idNumber` INT NOT NULL,
  `GroupNumber` INT NOT NULL,
  `Item` TEXT(10) NOT NULL,
  `Quantity` INT NOT NULL,
  `Borrowed` DATETIME NOT NULL,
  `Class_staffcol` DATETIME NOT NULL,
  PRIMARY KEY (`ClassCode`))
ENGINE = InnoDB;

USE `class_staff` ;

-- -----------------------------------------------------
-- Table `class_staff`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `class_staff`.`staff` ;

CREATE TABLE IF NOT EXISTS `class_staff`.`staff` (
  `ClassCode` INT(11) NOT NULL AUTO_INCREMENT,
  `idNumber` INT(11) NOT NULL,
  `GroupNumber` INT(4) NOT NULL,
  `Item` TINYTEXT NOT NULL,
  `Quantity` INT(11) NOT NULL,
  `Borrowed` TINYTEXT NOT NULL,
  `Returned` TINYTEXT NOT NULL,
  PRIMARY KEY (`ClassCode`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
